### ISSUE TITLE
Too many redirection errors

### ISSUE THREAD

**Issue by midorikocak** [midorikocak/authake#13]
Someone reported that with windows server and Cake 2.3.1 there are too many redirections issues. Is there anyone to help about this?

**Comment by misfotto** [comment]
explain better the issue, because i also had the same problem but solved, 'cause was an error on the controller login i wrote! :)

**Comment by stevensjn** [comment]
So glad you are working on this! Thank you. 

Your documentation clearly states that you can either use cake console to setup the plugin schema or "alternatively" use the provided db script. Unfortunately the cake console approach does not add the default records into the schema, while the provided script does, therefore you MUST execute the provided db script, or these redirect errors occur.

"You can create schema from plugin using command to console terminal when you are in your app folder:
Console/cake schema create -plugin Authake
Or Alternatively you can add the Authake/db/authake_clean.sql to your database."

Thanks again for sharing this plugin. 
- Jake

**Comment by midorikocak** [comment]
I deleted the schema
