### ISSUE TITLE
doesn't work with cakephp 2.3.1

### ISSUE THREAD

**Issue by Xenon69** [midorikocak/authake#16]
Installed and configured as described.

login "admin" / pw "admin" => not working
tried "root" / "admin" => redirected to "http://showcase.dev/aktifshemale/" !

maybe I did something wrong.

any hints ?

Fred

**Comment by midorikocak** [comment]
just reset the authake or change the authake_config.php with newer one

**Comment by Xenon69** [comment]
Hi, thanks for fast answer !

I don't know how to reset the authake nor how to generate a new authake_config.php

Is there somewhere a documentation about this ?

Thanks !

Fred

**Comment by midorikocak** [comment]
It's better if you directly re download the plugin from here. We had a pull
request previously. Also for resetting authake you go to the settings on
the main menu, but a think it's a little bit beta to try on an actual
project.

2013/4/2 Fred notifications@github.com
